### ISSUE TITLE
Participants interested in an Open Opportunities task should get a reply email signed by the Open Opportunities team.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas-open-opportunities#55]
Right now when someone presses the "I'm in" button they are sent an email saying "Thanks! The Midas Team".  This should be changed to read "Thanks! The Open Opportunities Team."

**Comment by dhcole** [comment]
I did a review of instances where `systemName` is used and it looks like it's always used a full string, and not an ID, so we can just change this line:

https://github.com/18F/midas/blob/devel/config/local.ex.js#L28

@ultrasaurus where's the best place to do this so that it only applies to the Open Opportunities instance?

**Comment by ultrasaurus** [comment]
We need to add it to:  https://github.com/18F/cloud-cutter/blob/master/chef/nodes/midas_aws.json

But you can't test it yet till you've got AWS access and your ssh key there.  I'll do the pull request. Can you add your ssh key?

Thanks!

**Comment by dhcole** [comment]
Ok, my key is in this PR: https://github.com/18F/cloud-cutter/pull/35

**Comment by ultrasaurus** [comment]
Didn't see that -- merged!

**Comment by ultrasaurus** [comment]
in process:
https://github.com/18F/cloud-cutter/commit/c96615a017b7bbcd898e664c298d37948d600c5e

**Comment by ultrasaurus** [comment]
Completed and deployed to production last week. @LisaLNelson will you accept?

**Comment by LisaLNelson** [comment]
accept
